### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by pedrogneri** [pedrogneri/gereco#38]
The software is internationalized, so  if you know any other language than already exists on the [bundles](https://github.com/pedrogneri/gereco/tree/master/src/main/resources/bundles) add a new string bundle in  [resources/bundles](https://github.com/pedrogneri/gereco/tree/master/src/main/resources/bundles).
If you don't know how internationalization works in java, [click here](https://docs.oracle.com/javase/tutorial/i18n/resbundle/propfile.html).
Feel free to improve translations too.

**Comment by jejoivanic** [comment]
Hi, can I add the spanish translation?

**Comment by pedrogneri** [comment]
> Hi, can I add the spanish translation?

Yes, of course :D

**Comment by jejoivanic** [comment]
Done! Please tell me if I missed something :D

**Comment by GauravMohla** [comment]
I can add it for German and French

**Comment by pedrogneri** [comment]
> I can add it for German and French

That would be really nice!

**Comment by Anca07** [comment]
Hi, I can add Romanian translations :)

**Comment by GauravMohla** [comment]
#48 added for the de, fr translations

**Comment by jsolovjo** [comment]
I can do for Russian and Estonian

**Comment by ManasaMaganti** [comment]
I can do it for Telugu which is one of the Indian languages

**Comment by shivamagarwal7** [comment]
@pedrogneri I can do it for Hindi.

**Comment by shivamagarwal7** [comment]
@pedrogneri, I have raised a pull request.

**Comment by PrathibhaS** [comment]
#57 Created translations for Tamil language

**Comment by enesacikoglu** [comment]
Let me add for turkish :)

**Comment by enesacikoglu** [comment]
> Let me add for turkish :)

https://github.com/pedrogneri/gereco/pull/70

**Comment by leonorader** [comment]
I can do Hungarian translation :)

**Comment by leonorader** [comment]
> I can do Hungarian translation :)

#76 :)
