### ISSUE TITLE
Create new unit tests

### ISSUE THREAD

**Issue by pedrogneri** [pedrogneri/gereco#39]
The software uses unit tests with JUnit but not all logic has test classes. Then add unit tests for the methods of the [helpers](https://github.com/pedrogneri/gereco/tree/master/src/main/java/helpers) package classes.

**Comment by shivamagarwal7** [comment]
@pedrogneri  can I take this up?

**Comment by PraveenMathew92** [comment]
Am working on it 
Please merge #47 as the unit test are written on top of that commit

**Comment by PraveenMathew92** [comment]
@sa160690 
Am working on [MatchesGenerator](https://github.com/pedrogneri/gereco/blob/master/src/main/java/helpers/MatchesGenerator.java)

You may pick up the others. In case of test failures, I have made a fix in #47, it is yet to be merged

Hope your fine with it

**Comment by shivamagarwal7** [comment]
@PraveenMathew92, yes sure. I will pick up other classes.

**Comment by shivamagarwal7** [comment]
@pedrogneri, I have raised a pull request.

**Comment by icougil** [comment]
can I give a hand @pedrogneri ?

**Comment by icougil** [comment]
I've send you a PR (just for the `PdfTableGenerator`)  ;-)

**Comment by bit-man** [comment]
Working on ` TeamGroupsManager`

**Comment by bit-man** [comment]
Workgin on ` UTF8Control`
