### ISSUE TITLE
Component to change language of the software

### ISSUE THREAD

**Issue by pedrogneri** [pedrogneri/gereco#52]
Add a component in the [initial.fxml](https://github.com/pedrogneri/gereco/blob/master/src/main/resources/views/initial.fxml) and in [institution-config.fxml](https://github.com/pedrogneri/gereco/blob/master/src/main/resources/views/external-forms/institution-config.fxml) to change language in software with all languages it contains in [bundles](https://github.com/pedrogneri/gereco/tree/master/src/main/resources/bundles)

To change language in Java, use: 
```Locale.setDefault(new Locale("language-code", "country-code")) ```
or just ```Locale.setDefault(new Locale("language-code")) ```

Language and country code can be find on the bundles name.

**Comment by Ashiroq** [comment]
Hi, I'm working on this one.
