### ISSUE TITLE
Encoding language bug

### ISSUE THREAD

**Issue by pedrogneri** [pedrogneri/gereco#53]
Some languages don't use the UTF-8 encoding, and that causes a bug, because some characters are not recognized, so I need to resolve that.

Bugs like that in French:
![image](https://user-images.githubusercontent.com/27109836/67147954-40447d00-f270-11e9-9720-bd7f0ad3061a.png)

I have that same problem with UTF-8 when I create a pt-br bundle, but the way I resolve that need a class specified to UTF-8 encoding and languages like french use different enconding. So I need a better way to do that.

**Comment by shivamagarwal7** [comment]
@pedrogneri, can you please elaborate more on the issue?

**Comment by shivamagarwal7** [comment]
Hi @pedrogneri, is it possible that your original file is not encoded in UTF-8:
https://stackoverflow.com/questions/48285219/why-french-characters-dont-work-using-utf-8-with-java

**Comment by pedrogneri** [comment]
> Hi @pedrogneri, is it possible that your original file is not encoded in UTF-8:
> https://stackoverflow.com/questions/48285219/why-french-characters-dont-work-using-utf-8-with-java

It may be that, thanks :)
